### ISSUE TITLE
Typographical Error: `treshold` should be `threshold`

### ISSUE THREAD

**Issue by bm3n** [Honatas/bootstrap-4-autocomplete#29] opened 2021-09-23 16:19 UTC
The option `treshold` should be spelled `threshold`

**Comment by nisegami** [comment] 2021-09-30 12:05
Seems to be a duplicate of #7

**Closed as completed** 2021-09-30 12:10 UTC

**Comment by Honatas** [comment] 2021-09-30 12:12
> Seems to be a duplicate of #7

And it acutally is, therefore I'm closing it. =)
